### ISSUE TITLE
Getting exception in latest version

### ISSUE THREAD

**Issue by gnw** [ruffiem/generator-angular2-application-scaffolder#4]
Hi,
  This morning I did a 'npm install -g generator-angular2-application-scaffolder'.  When I run yoeman, I get the following exception:

% yo angular2-application-scaffolder
Native thread-sleep not available.
This will result in much slower performance, but it will still work.
You should re-install spawn-sync or upgrade to the lastest version of node if possible.
Check /usr/local/lib/node_modules/generator-angular2-application-scaffolder/node_modules/yeoman-generator/node_modules/cross-spawn/node_modules/spawn-sync/error.log for more details
? What is the name of your app? (kebab-case)

events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Object [object Object] has no method 'then'
    at Base.prompt (/usr/local/lib/node_modules/generator-angular2-application-scaffolder/node_modules/yeoman-generator/lib/base.js:232:45)
    at module.exports.yeoman.Base.extend.prompting (/usr/local/lib/node_modules/generator-angular2-application-scaffolder/generators/app/index.js:17:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-angular2-application-scaffolder/node_modules/yeoman-generator/lib/base.js:431:23)
    at /usr/local/lib/node_modules/generator-angular2-application-scaffolder/node_modules/yeoman-generator/node_modules/run-async/index.js:26:25
    at invokeResolver (/usr/local/lib/node_modules/generator-angular2-application-scaffolder/node_modules/yeoman-generator/node_modules/run-async/node_modules/pinkie-promise/node_modules/pinkie/index.js:44:3)
    at new Promise (/usr/local/lib/node_modules/generator-angular2-application-scaffolder/node_modules/yeoman-generator/node_modules/run-async/node_modules/pinkie-promis

Please let me know if I can provide more info.

Thanks,
  Gary

**Comment by ruffiem** [comment]
Thanks for the message Gary. Did you upgrade to the last version of yeoman
before running the yo installer ?

**Comment by gnw** [comment]
Yes, I did.  I found the issue.  I was using 0.10.33 version of node.js.  When I upgraded to 6.x, everything working fine now.  Sorry for the bother!
