### ISSUE TITLE
Error when creating project

### ISSUE THREAD

**Issue by alaporterie** [ruffiem/generator-angular2-application-scaffolder#5]
Hi,

I get an error when I tried to create the project with:
yo angular2-application-scaffolder

? What is the name of your app? (kebab-case)

events.js:154
      throw er; // Unhandled 'error' event
      ^

TypeError: this.env.adapter.prompt(...).then is not a function
    at Base.prompt (/usr/local/lib/node_modules/generator-angular2-application-scaffolder/node_modules/yeoman-generator/lib/base.js:232:45)
    at module.exports.yeoman.Base.extend.prompting (/usr/local/lib/node_modules/generator-angular2-application-scaffolder/generators/app/index.js:17:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-angular2-application-scaffolder/node_modules/yeoman-generator/lib/base.js:431:23)
    at /usr/local/lib/node_modules/generator-angular2-application-scaffolder/node_modules/yeoman-generator/node_modules/run-async/index.js:26:25
    at /usr/local/lib/node_modules/generator-angular2-application-scaffolder/node_modules/yeoman-generator/node_modules/run-async/index.js:25:19
    at /usr/local/lib/node_modules/generator-angular2-application-scaffolder/node_modules/yeoman-generator/lib/base.js:432:9
    at processImmediate [as _immediateCallback](timers.js:383:17)

I tried with the last version. Your scaffolder looks very useful.
Could you help me please ?

Thanks,
Anthony

**Comment by ruffiem** [comment]
Hello, you need to update yeoman

``` bash
$ npm -g install yo
```

Cheers

**Comment by alaporterie** [comment]
Thank you, it worked!

Cheers
